name: carbon_flutter
description: UI library that translates IBM's Carbon Design System into Flutter
version: 0.11.1
homepage: https://github.com/NourEldinShobier/carbon-flutter

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  vector_math: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/

  fonts:
    - family: IBMPlexSans-Thin
      fonts:
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
    - family: IBMPlexSans-ExtraLight
      fonts:
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
    - family: IBMPlexSans-Light
      fonts:
        - asset: assets/fonts/IBMPlexSans-Light.ttf
    - family: IBMPlexSans-Regular
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
    - family: IBMPlexSans-Medium
      fonts:
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
    - family: IBMPlexSans-SemiBold
      fonts:
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
    - family: IBMPlexSans-Bold
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf

    # icons

    - family: CIcons
      fonts:
        - asset: assets/carbon_icons/icons.ttf
